### ISSUE TITLE
Product Info page display wrong item infomation

### ISSUE THREAD

**Issue by JinXJinX** [rash0/Vue-Ecom#2]
I think the following code has some problem, which is display wrong item on info page. When an item is clicked on /products page, item data will be pushed to state.infoPage. So 'info' page should display the last item in the state.infoPage, not the first item in the array. 

https://github.com/rash0/Vue-Ecom/blob/588f8d27fd2650b8addfa99e52e22b961a867fe1/src/store.js#L140-L144

And also, the files in dist/ folder looks is not the most recent compiled code generated by 'npm run build'

btw, I think it's a nice project with elegant UI.

**Comment by rash0** [comment]
Sorry fro the late replay, Yes you are right that the displaying of `info page` has a problem, but its caused by the `createPersistedState` in the store, I disable it already

The `infoLength` function is a `computed` function, which removes the first item in the array every time it gets invoked......so mainly every time an item is `pushed` into the `infoPage` array, an item get removed by the `infoLength` function....the persistent state was bugging this process somehow...

and yes you are right also about the /dist folder, I already updated it, and I really appreciate your opinion and taking time to look to the code and give me feedback 🤘 ☺️
